.gitignore
electron/main.js
electron/resources/splash/splash-screen.html
package.json
yarn.lock

This pr adds the auto updating functionality to the KeepKey client. 
**Note:** the `.blockmap` and `latest.yml` files need to be included in the release
closes #6
Each update release needs to include the `.blockmap` and `latest.yml` files
- Set up local environment
- Launch the electron app
- Notice the new update process and splash screen

feat: add auto updating functionality

---

electron/src/keepkey.ts
electron/src/main.ts
src/components/Modals/Bootloader/Bootloader.tsx
src/components/Modals/Firmware/Firmware.tsx
src/components/Modals/Pair/Pair.tsx
src/components/Modals/Sign/Sign.tsx
src/context/PortfolioProvider/PortfolioContext.tsx
src/context/WalletProvider/KeepKey/components/Connect.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/WalletProvider.tsx

Many of the IPC events had different names and formats. This PR sets a standard format for these events
There were a lot of events and I might have missed a few, these need to be checked for.

feat: standardize events

---

electron/src/bridge.ts
src/context/WalletProvider/WalletProvider.tsx

Feature expanded api

---

electron/src/bridge.ts
src/context/WalletProvider/WalletProvider.tsx

hotfix bridge

---

src/context/WalletProvider/KeepKey.tsx
src/context/WalletProvider/WalletProvider.tsx

fix pubkeys

---

package.json

keepkey UX work

---

src/components/Modals/HardwareError/HardwareError.tsx

cleanup UX

---

electron/api/dist/swagger.json
electron/src/bridge/controllers/b-device-controller.ts
electron/src/bridge/controllers/c-index.controller.ts
electron/src/bridge/controllers/d-pubkey-controller.ts
electron/src/bridge/controllers/e-sign-controller.ts
electron/src/bridge/controllers/f-developer-controller.ts
electron/src/bridge/controllers/g-recovery-controller.ts
electron/src/bridge/controllers/h-device-info-controller.ts
electron/src/bridge/routes/routes.ts
src/context/WalletProvider/WalletProvider.tsx
src/pages/ConnectWallet/ConnectWallet.tsx

expand API for all keepkey calls

---

package.json
sample.env
src/config.ts
src/features/defi/components/Withdraw/Withdraw.tsx
src/pages/Defi/components/OverviewHeader.tsx
src/pages/Defi/hooks/useFoxyBalances.tsx
src/plugins/cosmos/components/modals/Staking/views/Overview.tsx
src/plugins/cosmos/components/modals/Staking/views/StakeBroadcast.tsx
src/plugins/cosmos/components/modals/Staking/views/UnstakeBroadcast.tsx

Release 1.5.0

---

headers.js

header expand

---

src/context/AppProvider/AppContext.tsx

fix disconnect not showing modal

---

package.json
react-app-rewired/headers/csps/wallets/walletconnect.ts
src/kkdesktop/walletconnect/service.ts
src/kkdesktop/walletconnect/types.ts
src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx
src/state/slices/portfolioSlice/utils.ts
yarn.lock

wallet connect working with eth uniswap and shapeshift

wallet connect working with eth uniswap and shapeshift

---

src/assets/translations/en/main.json
src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx

Add Developer tools launch to App

---

electron/src/bridge/controllers/c-index.controller.ts
electron/src/utils.ts

always on top behaviour

---

src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/components/Layout/Header/NavBar/SubmenuHeader.tsx
src/components/Layout/Header/NavBar/UserMenu.tsx
src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx

kk settings dropdown

---

electron/src/bridge/index.ts
src/App.tsx
src/components/Modals/UpdateBootloader/UpdateBootloader.tsx

Show bootloader versions

---

electron/src/bridge/index.ts
electron/src/bridge/kk-controller/index.ts
electron/src/bridge/kk-controller/types.ts
package.json
src/context/WalletProvider/KeepKey/components/Pin.tsx
yarn.lock

Bring in hardware controller

---

electron/src/bridge/kk-controller/index.ts

fi when plugged in on start

---

electron/src/bridge/controllers/b-device-controller.ts

fix unplug

---

.gitignore
src/assets/translations/en/main.json
src/pages/ConnectWallet/ConnectWallet.tsx

add buy keepkey button

---

package.json
src/Routes/Routes.tsx
src/Routes/RoutesCommon.tsx
src/assets/translations/en/main.json
src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyVersions.ts
src/pages/Pairings/Pairings.tsx

fix version bug, add pairings page

---

src/Routes/RoutesCommon.tsx
src/components/AssetSearchKK/AssetIcon.tsx
src/components/AssetSearchKK/AssetList.tsx
src/components/AssetSearchKK/AssetRow.tsx
src/components/AssetSearchKK/AssetSearchKK.tsx
src/components/AssetSearchKK/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.test.ts
src/components/AssetSearchKK/helpers/filterAssetsBySearchTerm/filterAssetsBySearchTerm.ts
src/components/Breadcrumbs/Breadcrumbs.tsx
src/components/KKAssetAccountDetails/AssetHeader/AccountLabel.tsx
src/components/KKAssetAccountDetails/AssetHeader/AssetActions.tsx
src/components/KKAssetAccountDetails/AssetHeader/AssetDescription.tsx
src/components/KKAssetAccountDetails/AssetHeader/AssetHeader.tsx
src/components/KKAssetAccountDetails/AssetHeader/AssetIcon.tsx
src/components/KKAssetAccountDetails/AssetHeader/AssetMarketData.tsx
src/components/KKAssetAccountDetails/KKAssetAccountDetails.tsx
src/context/WalletProvider/KeepKeyProvider.tsx
src/pages/Assets/Assets.tsx
src/pages/Assets/KeepkeyAsset.tsx

search all assets layout and data routing

search all assets part 1

---

electron/src/main.ts
src/Routes/RoutesCommon.tsx
src/assets/translations/en/main.json
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/actions.ts
src/pages/Browser/Browser.tsx
src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx

in app browser

---

src/components/Modals/kkVote/KKVote.tsx
src/pages/Leaderboard/Leaderboard.tsx
src/pages/Leaderboard/helpers/LeaderboardTable.tsx
src/pages/Leaderboard/helpers/erc20Abi.tsx

approve & vote transactions working in app

approve & vote transactions

---

src/components/Modals/kkVote/KKVote.tsx
src/components/Modals/kkVote/utils.ts
src/pages/Leaderboard/Leaderboard.tsx

vote & approval state improvements

---

src/components/Layout/Header/NavBar/NavBar.tsx
src/components/Modals/Receive/ReceiveInfo.tsx
src/components/Modals/Send/views/Address.tsx
src/pages/Browser/Browser.tsx

bunch of fixes

---

electron/resources/splash/splash-screen.html
electron/src/bridge/index.ts
electron/src/updater.ts

hacky fix initialize freeze

---

src/components/Layout/Header/Header.tsx
src/components/Layout/Header/NavBar/FiatRamps.tsx
src/pages/Dashboard/Dashboard.tsx

Move buy bitcoin button

---

electron/src/bridge/controllers/e-sign-controller.ts
electron/src/utils.ts

fix for sdk calls sign

---

electron/src/bridge/controllers/c-index.controller.ts
electron/src/bridge/controllers/d-pubkey-controller.ts
electron/src/bridge/index.ts

pass last known state to status endpoint

---

package.json
scripts/bootstrap.sh
scripts/git-hooks/pre-push.sh
scripts/install-hooks.sh
src/components/Layout/Header/Header.tsx
src/components/Layout/Header/NavBar/FiatRamps.tsx
src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/components/Modals/Settings/SettingsList.tsx
src/context/WalletProvider/KeepKey/components/Pin.tsx
src/pages/ConnectWallet/ConnectWallet.tsx

* Adds pre-push hook to run lint script prior to push
*  Adds bootstrap script to install git hooks and perform any other repo initialization tasks
*  Ideally, the lint script would be run in a pre-commit git hook, but the lint script is too slow for this to be practical
* Fix lint errors
closes #

feat: add pre-push git hook

---

electron/src/bridge/index.ts
electron/src/bridge/routes/routes.ts
electron/src/tray.ts

fix merge issues

---

electron/src/bridge/index.ts

remove duplicate error event

---

electron/src/bridge/index.ts
electron/src/bridge/kk-controller/index.ts
electron/src/tray.ts
electron/src/updater.ts

fix trey again

---

electron/resources/splash/splash-screen.html
electron/src/bridge/index.ts

Fix claimed

---

electron/src/bridge/controllers/b-device-controller.ts
electron/src/bridge/index.ts
electron/src/bridge/kk-state-controller/index.ts
src/components/AssetSearchKK/AssetIcon.tsx
src/components/Layout/Header/NavBar/UserMenu.tsx
src/components/Modals/HardwareError/HardwareError.tsx
src/context/WalletProvider/WalletContext.tsx
src/context/WalletProvider/WalletProvider.tsx

- send frontend a device busy message if busy
- Lets us not do certain things if busy (like trying to reconnect)

device busy ipc message and retry button

---

electron/src/bridge/controllers/b-device-controller.ts
electron/src/bridge/controllers/c-index.controller.ts
electron/src/bridge/controllers/d-pubkey-controller.ts
electron/src/bridge/controllers/f-developer-controller.ts
electron/src/bridge/controllers/g-recovery-controller.ts
electron/src/bridge/controllers/h-device-info-controller.ts
electron/src/bridge/index.ts
electron/src/main.ts
electron/src/settings.ts
electron/src/tray.ts
electron/src/utils.ts

differentiate between the bridge being a tcp server and the wallet itself: 
isWalletBridgeRunning() means both wallet and tcp bridge are good to go

better state manegement around tcp bridge, kk controller and tray

---

electron/src/bridge/controllers/c-index.controller.ts
electron/src/main.ts
src/assets/translations/en/main.json
src/kkdesktop/walletconnect/service.ts
src/pages/Pairings/Pairings.tsx

pairing history, #239

---

electron/src/bridge/kk-state-controller/index.ts
electron/src/main.ts
src/App.tsx
src/components/Modals/Loading/Loading.tsx
src/context/AppProvider/AppContext.tsx
src/context/ModalProvider/ModalProvider.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/WalletContext.tsx
src/context/WalletProvider/WalletProvider.tsx

loaders and cleanup state

---

electron/src/helpers/controllers/b-device-controller.ts
electron/src/tcpBridge.ts
electron/src/windowListeners.ts
src/components/Modals/Loading/Loading.tsx

fix close on pin

---

src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/components/Layout/Header/NavBar/WalletConnectedMenu.tsx
src/plugins/walletConnectToDapps/components/modal/connectModal.tsx

wallet connect auto populate and keepkey menu changes

---

src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/components/Modals/UpdateKeepKey/UpdateKeepKey.tsx
src/context/AppProvider/AppContext.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/WalletProvider.tsx

fix unplug modal not showing on d/c

---

electron/src/helpers/globalState.ts
src/components/Layout/Header/NavBar/ChainMenu.tsx
src/components/Layout/Header/NavBar/KeepKey/AwaitKeepKey.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/WalletContext.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx

Remove buggy ass load function in WalletProvider
closes #

Remove load

---

src/assets/translations/en/main.json
src/components/AssetAccountDetails.tsx
src/components/AssetAccountNft.tsx

Added NFT section to Ethereum asset page
closes #

Nft allocation

---

src/kkdesktop/walletconnect/service.ts
src/plugins/walletConnectToDapps/components/modal/callRequest/ContractInteractionBreakdown.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx

fix fee data race condition and undefined tx value bug

Walletconnect fixes

---

electron/src/helpers/controllers/b-device-controller.ts
electron/src/helpers/routes/routes.ts
electron/src/ipcListeners.ts
src/assets/translations/en/main.json
src/context/WalletProvider/KeepKey/components/Label.tsx

Freeze fix

---

.github/ISSUE_TEMPLATE/bounty.yml
.github/ISSUE_TEMPLATE/config.yml
CONTRIBUTING.md
README.md
src/components/Layout/Header/SideNavContent.tsx
src/lib/consoleArt.ts

update discord links

---

src/components/KKAssetAccountDetails/KKAssetAccountDetails.tsx
src/components/KKAssetAccountDetails/KKAssetHeader/KKAssetHeader.tsx
src/components/Modals/kkVote/KKVote.tsx
src/pages/Dashboard/DashboardSidebar.tsx

Update vote modal

---

electron/src/helpers/kk-state-controller/index.ts
src/App.tsx
src/components/Layout/Header/NavBar/KeepKey/KeepKeyMenu.tsx
src/components/Layout/Header/NavBar/KeepKey/Modals/Wipe.tsx
src/components/Modals/Loading/Loading.tsx
src/components/Modals/UpdateKeepKey/HardwareError/HardwareError.tsx
src/components/Modals/UpdateKeepKey/UpdateKeepKey.tsx
src/context/WalletProvider/KeepKey/components/Label.tsx
src/context/WalletProvider/KeepKey/hooks/useKeepKeyCancel.ts
src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
src/context/WalletProvider/WalletContext.tsx
src/context/WalletProvider/WalletProvider.tsx
src/context/WalletProvider/WalletViewsSwitch.tsx
src/pages/ConnectWallet/ConnectWallet.tsx

Fix boarding flow modals

---

electron/src/helpers/bridgeLogger.ts

Fix log crash

---

src/context/WalletProvider/web3byChainId.ts
src/kkdesktop/walletconnect/service.ts
src/plugins/walletConnectToDapps/WalletConnectBridgeProvider.tsx
src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/ContractInteractionBreakdown.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx

Known issues:
- some sites have trouble after switching evm chains while connected (uniswap, I dont think theres much we can do about it)
- cant yet switch chains from app side
- need error handling on tx build / broadcast failures
- gas fees sometimes estimated way too high and thinks user doesnt have enough balance
- need to convert fee amount to usd instead of showing $4.20

Walletconnect multichain

---

electron/src/ipcListeners.ts

set max listeners

---

src/context/WalletProvider/web3byChainId.ts
src/kkdesktop/walletconnect/service.ts
src/pages/ConnectWallet/ConnectWallet.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/CallRequestModal.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/GasFeeEstimateLabel.tsx
src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx

Fix price data

---

src/context/WalletProvider/web3byChainId.ts
src/kkdesktop/walletconnect/service.ts
src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx
src/plugins/walletConnectToDapps/components/header/WalletConnectToDappsHeaderButton.tsx

walletconnect switch chain partially implemented

switch walletconnect chain part 1

---

src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx

wc gasprice fix

---

src/kkdesktop/walletconnect/service.ts
src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx

use correct chain from walletconnect

use correct chain from walletconnect

---

src/kkdesktop/walletconnect/service.ts
src/plugins/walletConnectToDapps/components/header/DappHeaderMenuSummary.tsx

walletconnect switch networks bug fixes

walletconnect switch networks bug fixes

---

.github/workflows/build-electron.yml
.pnp.cjs
.yarnrc.yml
package.json
packages/keepkey-desktop-app/.env
packages/keepkey-desktop-app/package.json
packages/keepkey-desktop-app/scripts/build.ts
packages/keepkey-desktop/package.json
packages/keepkey-desktop/scripts/build.ts
yarn.lock

This reverts commit 2e89ae1612c3163b49af725c99c3cf3a95320a19.

Revert "Release candidate (#375)"

---

packages/keepkey-desktop-app/src/plugins/walletConnectToDapps/components/modal/callRequest/SignMessageConfirmation.tsx

strip 0x off front of hex string if it exists

strip 0x off front of hex string if it exists

---

packages/keepkey-desktop-app/src/plugins/walletConnectToDapps/WalletConnectBridgeProvider.tsx

fix walletconnect session

---

packages/keepkey-desktop-app/src/context/WalletProvider/KeepKey/components/Label.tsx
packages/keepkey-desktop-app/src/context/WalletProvider/KeepKey/components/Pin.tsx
packages/keepkey-desktop-app/src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
packages/keepkey-desktop-app/src/context/WalletProvider/WalletContext.tsx
packages/keepkey-desktop-app/src/context/WalletProvider/WalletProvider.tsx

fix dont metch pins

---

packages/keepkey-desktop-app/src/context/WalletProvider/KeepKey/components/Pin.tsx
packages/keepkey-desktop-app/src/context/WalletProvider/KeepKey/hooks/useKeepKeyEventHandler.ts
packages/keepkey-desktop/package.json

dont enable pin buttons until 3 seconds has elapsed

---

packages/keepkey-desktop-app/src/plugins/walletConnectToDapps/components/modal/callRequest/ContractInteractionBreakdown.tsx
packages/keepkey-desktop-app/src/plugins/walletConnectToDapps/components/modal/callRequest/SendTransactionConfirmation.tsx
packages/keepkey-desktop/package.json

fix crash when closing walletconnect confirm modal

fix crash when closing walletconnect confirm modal

---

packages/keepkey-desktop-app/src/components/Layout/Header/NavBar/NavBar.tsx

Only show authenticator if firmware supports it

Only show authenticator if firmware supports it

---

.pnp.cjs
.yarn/cache/@babel-runtime-npm-7.20.7-69d8df458c-4629ce5c46.zip
.yarn/cache/tinycolor2-npm-1.4.2-462ba30c26-57ed262e08.zip
.yarn/cache/tinycolor2-npm-1.5.2-0898381e92-9df1ea9a98.zip
packages/keepkey-desktop-app/src/assets/translations/en/main.json
packages/keepkey-desktop-app/src/components/Modals/DappClick/DappClick.tsx
packages/keepkey-desktop-app/src/context/ModalProvider/ModalProvider.tsx
packages/keepkey-desktop-app/src/plugins/walletConnectToDapps/components/DappRegistryGrid.tsx
yarn.lock

dapp verify modal on click dapp

dapp verify modal on click dapp

---

packages/keepkey-desktop-app/src/assets/translations/en/main.json
packages/keepkey-desktop-app/src/components/Modals/AddAuthenticatorAccount/AddAuthenticatorAccount.tsx
packages/keepkey-desktop-app/src/lib/readQrCode.ts
packages/keepkey-desktop-app/src/pages/Authenticator/Authenticator.tsx
packages/keepkey-desktop/package.json

Amitoj release candidate

---

packages/keepkey-desktop/src/tcpBridge.ts
packages/keepkey-sdk-server/src/controllers/ethereum.ts

should test ETH send on this before merge (edit: tested, works fine)

fix sdk logging

---

packages/keepkey-desktop-app/src/assets/translations/pl/main.json

Added Polish translations
